"""
init_research.py — Scaffold a new autoresearch-skill project directory.

Usage:
    python init_research.py --goal "..." --metric "..." --direction {maximize|minimize} \
        [--target "..."] [--max-iterations 10] [--output ./my-research/]
"""

import argparse
import os
import shutil
import stat
import tempfile
import textwrap
from datetime import datetime
from pathlib import Path
from typing import Callable, Optional

RESEARCH_TEMPLATE = """\
# Research: {title}

> **Scaffold status: INCOMPLETE.** This file contains labeled placeholders. It is not an approved
> experiment plan. Complete and validate every placeholder through explicit /start-work before any
> mutation or evaluator execution.

## Goal
{goal}

## Success Metric
- **Metric:** {metric}
- **Target:** {target}
- **Direction:** {direction}

## Constraints
- **Max iterations:** {max_iterations}
- **Time budget per experiment:** 5 minutes
- **Pause for review every:** never
- **Evaluator:** {evaluator}
- **Keep policy:** {keep_policy}
- **Guard:** {guard}
- **Noise runs:** {noise_runs}
- **Min delta:** {min_delta}

## Current Approach
_Describe your current baseline here._

## Search Space
- **Allowed changes:** _Define what the agent can modify._
- **Forbidden changes:** _Define what must NOT change._

## Context & References
_Add relevant papers, docs, or URLs here._

---

## History
| # | Change | Metric | Result | Timestamp |
|---|--------|--------|--------|-----------|
| 0 | Baseline | TBD | -- | {date} |
"""

LOG_TEMPLATE = """\
# Research Log

> Auto-generated by init_research.py on {date}
> Goal: {goal}

---

"""

TSV_HEADER = "iteration\tmetric_value\tdelta\tdelta_pct\tstatus\tdescription\tevaluator_source\ttimestamp\n"
TSV_BASELINE = "0\tTBD\t-\t-\tbaseline\tInitial state\tagent\t{date}\n"
SYSTEM_PATH_ALIASES = {
    "/etc": "/private/etc",
    "/tmp": "/private/tmp",
    "/var": "/private/var",
}


def _identity(path: Path):
    try:
        value = path.lstat()
    except FileNotFoundError:
        return None
    return (
        value.st_dev,
        value.st_ino,
        stat.S_IFMT(value.st_mode),
        value.st_ctime_ns,
        getattr(value, "st_birthtime_ns", 0),
    )


def _allowed_system_alias(path: Path) -> bool:
    expected = SYSTEM_PATH_ALIASES.get(str(path))
    return expected is not None and os.path.realpath(str(path)) == expected


def validate_output_tree(output: Path) -> Path:
    """Reject symlink ancestors, symlink roots, and non-regular tree entries."""
    absolute = Path(os.path.abspath(str(output)))
    for ancestor in reversed(absolute.parents):
        try:
            mode = ancestor.lstat().st_mode
        except FileNotFoundError:
            continue
        if stat.S_ISLNK(mode) and not _allowed_system_alias(ancestor):
            raise RuntimeError(f"refusing symlink output ancestor: {ancestor}")
        if not stat.S_ISLNK(mode) and not stat.S_ISDIR(mode):
            raise RuntimeError(f"refusing non-directory output ancestor: {ancestor}")

    root_identity = _identity(absolute)
    if root_identity is None:
        return absolute
    root_mode = absolute.lstat().st_mode
    if stat.S_ISLNK(root_mode):
        raise RuntimeError(f"refusing symlink output root: {absolute}")
    if not stat.S_ISDIR(root_mode):
        raise RuntimeError(f"refusing non-directory output root: {absolute}")

    for current, directories, files in os.walk(str(absolute), followlinks=False):
        for name in directories + files:
            candidate = Path(current) / name
            mode = candidate.lstat().st_mode
            if stat.S_ISLNK(mode):
                raise RuntimeError(f"refusing symlink output entry: {candidate}")
            if not (stat.S_ISDIR(mode) or stat.S_ISREG(mode)):
                raise RuntimeError(f"refusing special output entry: {candidate}")
    return absolute


def atomic_publish(output: Path, populate: Callable[[Path], None]) -> None:
    """Populate a sibling staging tree and publish it with rollback."""
    output = validate_output_tree(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output = validate_output_tree(output)
    stage = Path(tempfile.mkdtemp(prefix=f".{output.name}.stage-", dir=str(output.parent)))
    parent_identity = _identity(output.parent)
    output_identity = _identity(output)
    backup = None
    published = False
    try:
        if output_identity is not None:
            shutil.copytree(str(output), str(stage), dirs_exist_ok=True, symlinks=True)
            validate_output_tree(stage)
        populate(stage)
        validate_output_tree(stage)
        if _identity(output.parent) != parent_identity or _identity(output) != output_identity:
            raise RuntimeError("output identity changed before publication")

        if output_identity is not None:
            backup = Path(tempfile.mkdtemp(prefix=f".{output.name}.backup-", dir=str(output.parent)))
            backup.rmdir()
            os.replace(str(output), str(backup))
            try:
                os.replace(str(stage), str(output))
            except BaseException:
                os.replace(str(backup), str(output))
                backup = None
                raise
            shutil.rmtree(str(backup))
            backup = None
        else:
            os.replace(str(stage), str(output))
        published = True
    finally:
        if not published and stage.exists():
            shutil.rmtree(str(stage))


def goal_to_title(goal: str) -> str:
    """Convert a goal string to a short title (first 8 words, title-cased)."""
    words = goal.split()
    short = " ".join(words[:8])
    if len(words) > 8:
        short += "..."
    return short.title()


def remove_known_run_artifacts(output: Path) -> list:
    """Remove only prior-run files owned by this workflow."""
    candidates = [output / name for name in ["final_report.md", "results.png", ".autoresearch-loop.pid"]]
    for artifact in candidates:
        if artifact.is_symlink():
            raise RuntimeError(f"refusing to remove symlink run artifact: {artifact}")
        if artifact.exists() and not artifact.is_file():
            raise RuntimeError(f"refusing to remove non-file run artifact: {artifact}")

    removed = []
    for artifact in candidates:
        if artifact.is_file():
            artifact.unlink()
            removed.append(artifact.name)
    return removed


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Scaffold a new autoresearch-skill project.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Example:
              python init_research.py \\
                --goal "Optimize sorting algorithm performance" \\
                --metric "execution_time_seconds" \\
                --direction minimize \\
                --target "< 0.5" \\
                --max-iterations 20 \\
                --output ./sort-research/
        """),
    )
    parser.add_argument("--goal", required=True, help="Research goal description.")
    parser.add_argument("--metric", required=True, help="Metric name to track (e.g. accuracy, execution_time_seconds).")
    parser.add_argument(
        "--direction",
        required=True,
        choices=["maximize", "minimize"],
        help="Whether to maximize or minimize the metric.",
    )
    parser.add_argument("--target", default="TBD", help="Target value or expression (e.g. '> 0.9', '< 0.5'). Default: TBD")
    parser.add_argument("--max-iterations", type=int, default=20, metavar="N", help="Maximum number of iterations. Default: 20")
    parser.add_argument("--output", default="./research/", metavar="PATH", help="Output directory. Default: ./research/")
    parser.add_argument("--evaluator", default=None, metavar="CMD",
        help="Evaluator command (e.g. 'python evaluate.py'). Must output JSON {pass:bool, score?:number}.")
    parser.add_argument("--keep-policy", default="score_improvement",
        choices=["score_improvement", "pass_only"],
        help="Keep policy: score_improvement (default) or pass_only.")
    parser.add_argument("--guard", default=None, metavar="CONDITION",
        help="Guard condition that must remain true (e.g. 'all unit tests pass'). Hard stop if violated.")
    parser.add_argument("--noise-runs", type=int, default=1, metavar="N",
        help="Number of runs to median over for noisy metrics. Default: 1")
    parser.add_argument("--min-delta", type=float, default=0.0, metavar="DELTA",
        help="Minimum improvement required to keep a change. Default: 0 (any improvement counts).")
    return parser.parse_args()


def scaffold(goal: str, metric: str, direction: str, target: str, max_iterations: int, output: Path,
             evaluator: Optional[str] = None, keep_policy: str = "score_improvement",
             guard: Optional[str] = None, noise_runs: int = 1, min_delta: float = 0.0) -> None:
    date = datetime.now().strftime("%Y-%m-%d")
    title = goal_to_title(goal)
    evaluator_str = f"`{evaluator}`" if evaluator else "_(none — agent judges manually)_"
    guard_str = guard if guard else "_(none)_"

    # Create workspace subdirectory
    workspace = output / "workspace"
    workspace.mkdir(exist_ok=True)

    # Write research.md
    research_md = output / "research.md"
    research_md.write_text(
        RESEARCH_TEMPLATE.format(
            title=title,
            goal=goal,
            metric=metric,
            target=target,
            direction=direction,
            max_iterations=max_iterations,
            evaluator=evaluator_str,
            keep_policy=keep_policy,
            guard=guard_str,
            noise_runs=noise_runs,
            min_delta=min_delta,
            date=date,
        )
    )

    # Write research_log.md
    log_md = output / "research_log.md"
    log_md.write_text(LOG_TEMPLATE.format(date=date, goal=goal))

    # Write autoresearch-results.tsv
    tsv_file = output / "autoresearch-results.tsv"
    tsv_file.write_text(TSV_HEADER + TSV_BASELINE.format(date=date))
    (output / "autoresearch_events.jsonl").write_text("")


def print_success(output: Path) -> None:
    print(f"\nINCOMPLETE scaffold created at: {output.resolve()}")
    print("\nFiles created:")
    for name in ["research.md", "research_log.md", "autoresearch-results.tsv", "autoresearch_events.jsonl"]:
        print(f"  {(output / name).resolve()}")
    print(f"  {(output / 'workspace').resolve()}/")
    print("\nNext steps — this is an incomplete scaffold with placeholders:")
    print("  1. Through explicit /start-work, fill in 'Current Approach' and 'Search Space'.")
    print("  2. Add context (papers, docs, code) under 'Context & References'.")
    print("  3. Run your baseline experiment and record it in the History table.")
    print("  4. Validate that every placeholder is resolved and record the baseline receipt.")
    print("  5. Only then may the approved finite loop continue through explicit /start-work.")


def main() -> None:
    args = parse_args()
    output = validate_output_tree(Path(args.output))

    if output.exists() and any(output.iterdir()):
        print(f"Warning: output directory '{output}' already exists and is not empty.")
        answer = input(
            "Reinitialize managed scaffold files while preserving regular user files? [y/N] "
        ).strip().lower()
        if answer != "y":
            print("Aborted.")
            return

    removed = []
    def populate(stage: Path) -> None:
        removed.extend(remove_known_run_artifacts(stage))
        scaffold(
            goal=args.goal,
            metric=args.metric,
            direction=args.direction,
            target=args.target,
            max_iterations=args.max_iterations,
            output=stage,
            evaluator=args.evaluator,
            keep_policy=args.keep_policy,
            guard=args.guard,
            noise_runs=args.noise_runs,
            min_delta=args.min_delta,
        )

    atomic_publish(output, populate)
    if removed:
        print(f"Removed stale run artifacts: {', '.join(removed)}")
    print_success(output)


if __name__ == "__main__":
    main()
