export const litOpenCodeGeneratedFrontmatterMarker = "litopencodeGenerated: true";
export const litOpenCodeLegacyGeneratedCommentMarker = "<!-- Generated by litopencode install. -->";

type Fence = {
  readonly marker: "`" | "~";
  readonly length: number;
};

export function stripUserFacingHtmlCommentLines(text: string): string {
  let fence: Fence | undefined;
  let htmlComment = false;
  return text
    .split("\n")
    .filter((line) => {
      const trimmed = line.trim();

      if (htmlComment) {
        htmlComment = !trimmed.includes("-->");
        return false;
      }

      const candidateFence = parseFence(trimmed);
      if (fence !== undefined) {
        if (candidateFence?.marker === fence.marker && candidateFence.length >= fence.length) fence = undefined;
        return true;
      }

      if (candidateFence !== undefined) {
        fence = candidateFence;
        return true;
      }

      if (trimmed.startsWith("<!--")) {
        htmlComment = !trimmed.includes("-->");
        return false;
      }

      return true;
    })
    .join("\n");
}

export function stripUserFacingBlankHtmlCommentLines(text: string): string {
  let fence: Fence | undefined;
  return text
    .split("\n")
    .filter((line) => {
      const trimmed = line.trim();
      const candidateFence = parseFence(trimmed);

      if (fence !== undefined) {
        if (candidateFence?.marker === fence.marker && candidateFence.length >= fence.length) fence = undefined;
        return true;
      }

      if (candidateFence !== undefined) {
        fence = candidateFence;
        return true;
      }

      return !/^<!--\s*-->$/.test(trimmed);
    })
    .join("\n");
}

export function hasLitOpenCodeGeneratedFileMarker(text: string): boolean {
  const normalized = text.replace(/\r\n/g, "\n");
  return hasGeneratedFrontmatterMarker(normalized) || firstNonEmptyBodyLine(normalized) === litOpenCodeLegacyGeneratedCommentMarker;
}

function parseFence(trimmed: string): Fence | undefined {
  const match = trimmed.match(/^(`{3,}|~{3,})/);
  if (match === null) return undefined;
  const marker = match[1][0] as "`" | "~";
  return { marker, length: match[1].length };
}

function hasGeneratedFrontmatterMarker(text: string): boolean {
  const frontmatter = frontmatterBlock(text);
  if (frontmatter === undefined) return false;
  return frontmatter.split("\n").some((line) => {
    const trimmed = line.trim();
    return trimmed === litOpenCodeGeneratedFrontmatterMarker || trimmed === 'litopencodeGenerated: "true"';
  });
}

function firstNonEmptyBodyLine(text: string): string | undefined {
  return bodyAfterFrontmatter(text)
    .split("\n")
    .map((line) => line.trim())
    .find((line) => line.length > 0);
}

function frontmatterBlock(text: string): string | undefined {
  if (!text.startsWith("---\n")) return undefined;
  const end = text.indexOf("\n---\n", 4);
  if (end === -1) return undefined;
  return text.slice(4, end);
}

function bodyAfterFrontmatter(text: string): string {
  if (!text.startsWith("---\n")) return text;
  const end = text.indexOf("\n---\n", 4);
  if (end === -1) return text;
  return text.slice(end + "\n---\n".length);
}
